In [4]:
import pandas as pd
df = pd.read_csv("model_outcome.csv")
df.head()

   Unnamed: 0  a1  a2  a3  y  r
0           1   1   0   1  0  0
1           2   0   0   0  1  1
2           3   0   1   0  0  1
3           4   0   0   0  1  0
4           5   0   0   0  0  1

In [59]:
def count_events(var1,x1, var2=None,x2=None, var3=None,x3=None):
  c = 0
  if var1 is None:
    c = df.shape[0]
  elif  var2 is None: 
      c = sum(df[var1]==x1)
  elif  var3 is None:
    for b1,b2 in zip(df[var1]==x1, df[var2]==x2):
      if b1 and b2:
        c += 1
  else:
    for b1,b2,b3 in zip(df[var1]==x1, df[var2]==x2, df[var3]==x3):
      if b1 and b2 and b3:
        c += 1
  return c 

# compute p(X=x|Y=y)
def p(var1,x1, var2=None,x2=None, var3=None,x3=None):
    return count_events(var1,x1, var2,x2, var3,x3) / count_events(var2,x2, var3,x3)

def show_p(var1,x1, var2=None,x2=None, var3=None,x3=None):
  if  var2 is None:
    print(f"  p({var1}={x1}) = {p(var1,x1)}")
  elif var3 is None:
    print(f"  p({var1}={x1} | {var2}={x2}) = {p(var1,x1,var2,x2)}")
  else:
    print(f"  p({var1}={x1} | {var2}={x2}, {var3}={x3}) = {p(var1,x1,var2,x2, var3,x3)}")

In [63]:
sc = ['a1', 'a2', 'a3']

print("Basic frequencies of characteristics:")
for var in sc:
  show_p(var,1)

print("\nTest for fairness type 1:")
for var in sc:
  show_p('r', 1, var, 0)
  show_p('r', 1, var, 1)

for var in sc:
  print(f"\nTest for fairness type 3 in {var}:")
  for rv in [0,1]:
    show_p('y', 1, 'r', rv)
    show_p('y', 1, 'r', rv, var, 0)
    show_p('y', 1, 'r', rv, var, 1)

Basic frequencies of characteristics:
  p(a1=1) = 0.51
  p(a2=1) = 0.21
  p(a3=1) = 0.1

Test for fairness type 1:
  p(r=1 | a1=0) = 0.32653061224489793
  p(r=1 | a1=1) = 0.3333333333333333
  p(r=1 | a2=0) = 0.21518987341772153
  p(r=1 | a2=1) = 0.7619047619047619
  p(r=1 | a3=0) = 0.3111111111111111
  p(r=1 | a3=1) = 0.5

Test for fairness type 3 in a1:
  p(y=1 | r=0) = 0.5970149253731343
  p(y=1 | r=0, a1=0) = 0.696969696969697
  p(y=1 | r=0, a1=1) = 0.5
  p(y=1 | r=1) = 0.5757575757575758
  p(y=1 | r=1, a1=0) = 0.625
  p(y=1 | r=1, a1=1) = 0.5294117647058824

Test for fairness type 3 in a2:
  p(y=1 | r=0) = 0.5970149253731343
  p(y=1 | r=0, a2=0) = 0.5967741935483871
  p(y=1 | r=0, a2=1) = 0.6
  p(y=1 | r=1) = 0.5757575757575758
  p(y=1 | r=1, a2=0) = 0.5882352941176471
  p(y=1 | r=1, a2=1) = 0.5625

Test for fairness type 3 in a3:
  p(y=1 | r=0) = 0.5970149253731343
  p(y=1 | r=0, a3=0) = 0.5967741935483871
  p(y=1 | r=0, a3=1) = 0.6
  p(y=1 | r=1) = 0.5757575757575758
  p(y=1 | r=1, a3=0) = 0.6071428571428571
  p(y=1 | r=1, a3=1) = 0.4